### ISSUE TITLE
Transmit buffer parameters of the QSPI/SPI functions can be of type `const uint8_t *`

### ISSUE THREAD

**Issue by ThiemoVanEngelen** [STMicroelectronics/stm32wbxx_hal_driver#2]
Currently, the pointer to the transmit buffers are of type `uint8_t *`. When a user wants to send a `static const uint8_t data[]` buffer, they need to either make a copy into RAM or cast away the const before passing it to for example `HAL_SPI_Transmit`. Both are undesirable and unnecessary as the buffer is never written. This is true for both the SPI and the QSPI functions.

**Comment by KRASTM** [comment]
Hello @ThiemoVanEngelen,

Thank you for the report.

Just to be clear, did you suggest that we add a **const** to the transmit buffer into the prototype functions for both SPI and QSPI functions.

With regards.

**Comment by ThiemoVanEngelen** [comment]
Hello @KRASTM 

That is indeed what I am suggesting. So for example 
`HAL_StatusTypeDef HAL_SPI_Transmit(SPI_HandleTypeDef *hspi, uint8_t *pData, uint16_t Size, uint32_t Timeout);` becomes 
`HAL_StatusTypeDef HAL_SPI_Transmit(SPI_HandleTypeDef *hspi, const uint8_t *pData, uint16_t Size, uint32_t Timeout);`

Kind Regards,

**Comment by KRASTM** [comment]
ST Internal Reference: 186501

**Comment by RJMSTM** [comment]
Hello,

I hope you are fine. The issue you reported has been fixed in the frame of version v1.14.4 of the stm32wbxx-hal-driver published recently on GitHub. Thank you again for having reported.
